# Generated by Django 5.0.3 on 2024-04-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_author_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
